# Generated by Django 2.1.2 on 2018-11-04 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perro',
            name='foto',
        ),
    ]
