# Generated by Django 2.1.2 on 2018-10-30 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_auto_20181025_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagenperro', models.FileField(blank=True, null=True, upload_to='myfolder/')),
                ('nombreperro', models.CharField(max_length=50)),
                ('Razaperro', models.CharField(max_length=100)),
                ('Descripción', models.CharField(max_length=300)),
                ('Estado', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='postulante',
            name='run',
            field=models.CharField(max_length=50),
        ),
    ]
